### PR TITLE
Add Glossary & Table of Contents

### PR DESCRIPTION
**Pull request by ajweeks**

### CODE REVIEW

**Comment by izzyreal** [comment]
Supercool that you're picking this up! 86e73487688fdd5108a09c99246bf16e054bf31b is certainly an improvement. Maybe some code comments might be a good idea, for example:

In the Ambient term example:
* `t` (I'm guessing "term")

In the Ground plane example:
* `n` (?)

In the Soft shadows `rand` example:
* `co` ("coordinate"?)

In Materials
* `m` in `col = vec3(0.18*m, 0.6-0.05*m, 0.2)` ("material index"?)

**Comment by ajweeks** [comment]
All fair points! I noticed there were a few missing parts in the materials section as well, so I filled it out a bit.

**Comment by izzyreal** [comment]
Great, it looks very clear now.

**Comment by huwb** [comment]
Looks great, nicely done!

**Pull request merged**
